export const SAVE_RESULTS = 'SAVE_RESULTS';
export const ADD_TO_LIST = 'ADD_TO_LIST';
export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
